### ISSUE TITLE
Remove captcha

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/geco#308]
<p>For accessibility</p>
<i>Imported from JIRA:
[GECO-392] Remove captcha
(original by Douglas Waldron)</i>

**Comment by dougwaldron** [comment]
Blocked by #291

**Comment by patdnr** [comment]
Captcha has already been removed.

![image](https://user-images.githubusercontent.com/113926513/199041528-40149f46-389a-4f90-9261-315ca93afa21.png)
